### ISSUE TITLE
The SSL cert expired on March 4

### ISSUE THREAD

**Issue by puyo** [AOGPN/server#4]
```
Common name: forum.opengovernment.org.au
SANs: forum.opengovernment.org.au, opengovernment.org.au
Valid from March 4, 2016 to March 4, 2017
Serial Number: 5cc4c4d323b841f6ab32ad931ceb926c
Signature Algorithm: sha256WithRSAEncryption
Issuer: StartCom Class 1 DV Server CA	
```

**Comment by equivalentideas** [comment]
Thanks for raising this @puyo :)

Looks like it's all good now, and we've moved to Lets Encrypt 🚀 

![screen shot 2017-04-06 at 12 36 41 pm](https://cloud.githubusercontent.com/assets/1239550/24735340/caba3d38-1ac5-11e7-8e26-03f46705a107.png)

**Comment by henare** [comment]
The forum.opengovernment.org.au certificate has indeed expired but we're not intending to fix this. I've opened #5 about retiring this server.
